// Re-export all lucide-react icons with camelCase aliases for convenience
import {
  Heart,
  Sparkles,
  Users,
  Calendar,
  MapPin,
  Mail,
  Gift,
  Camera,
  Music,
  ChevronRight,
  ChevronDown,
  Check,
  CheckCircle,
  Star,
  Quote,
  Menu,
  X,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Play,
  Pause,
  Clock,
  Globe,
  Shield,
  Zap,
  Palette,
  Layout,
  Image,
  MessageSquare,
  Eye,
  EyeOff,
  Monitor,
  Smartphone,
  Utensils,
  Cake,
  CreditCard,
  User,
  Plus,
  Trash,
  Upload,
  Save,
  Link,
  Copy,
  Rocket,
  BookOpen,
  Lock,
  Loader2,
} from "lucide-react";

// Create Icons namespace with camelCase aliases for compatibility
const Icons = {
  heart: Heart,
  sparkles: Sparkles,
  users: Users,
  calendar: Calendar,
  mapPin: MapPin,
  mail: Mail,
  gift: Gift,
  camera: Camera,
  music: Music,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  check: Check,
  checkCircle: CheckCircle,
  star: Star,
  quote: Quote,
  menu: Menu,
  x: X,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  play: Play,
  pause: Pause,
  clock: Clock,
  globe: Globe,
  shield: Shield,
  zap: Zap,
  palette: Palette,
  layout: Layout,
  image: Image,
  messageSquare: MessageSquare,
  eye: Eye,
  eyeOff: EyeOff,
  monitor: Monitor,
  smartphone: Smartphone,
  utensils: Utensils,
  cake: Cake,
  creditCard: CreditCard,
  user: User,
  plus: Plus,
  trash: Trash,
  upload: Upload,
  save: Save,
  link: Link,
  copy: Copy,
  rocket: Rocket,
  bookOpen: BookOpen,
  lock: Lock,
  loader2: Loader2,
};

export { Icons };